### ISSUE TITLE
Disarm doesn't actually disarm (although it appears as disarmed in Home)

### ISSUE THREAD

**Issue by jdshkolnik** [bryanbartow/homebridge-alarm.com#57]
My "Arrive Home" scene includes turning off the alarm. To test, I set alarm to Stay, run scene, and alarm shows as off in Home app but is actually still in Stay mode. I don't know if it's a limitation of the API.

**Comment by davidvanvo** [comment]
Are you setting the alarm to Stay via phone or the Alarm Panel? If the latter, that's expected because the Home app polls Alarm.com for changes. This polling only happens when you refresh or relaunch the app. There might be a timed poll running in the background, but I'm not close enough to the code to confirm.

**Comment by jdshkolnik** [comment]
I suspect you're right about the polling interval. I'll increase the disarm timer window and see what happens.
